In [16]:
import sys
sys.path.append("../../")

import matplotlib.pyplot as plt

from environments.Passive_T_Maze_Flag.env.env_passive_t_maze_flag import TMazeClassicPassive

In [17]:
corridor_length = 28
episode_timeout = corridor_length + 2 # * DEFAULT CONFIGURATION: T = L + 2
desired_reward = 1 # * DEFAULT

In [24]:
env = TMazeClassicPassive(episode_length=episode_timeout, 
                          corridor_length=corridor_length, 
                          goal_reward=desired_reward)

obs = env.reset(seed=42)  # * {y, hint, flag, noise}

done = False

obss = []
while not done:
    print(obs)
    obss.append(env.render())
    act = env.action_space.sample()
    obs, reward, done, info = env.step(act)

print(obs)
obss.append(env.render())
env.close()

[ 0. -1.  0. -1.]
[0. 0. 0. 1.]
[0. 0. 0. 1.]
[ 0.  0.  0. -1.]
[ 0.  0.  0. -1.]
[0. 0. 0. 1.]
[0. 0. 0. 0.]
[0. 0. 0. 1.]
[0. 0. 0. 1.]
[0. 0. 0. 1.]
[0. 0. 0. 1.]
[ 0.  0.  0. -1.]
[0. 0. 0. 1.]
[0. 0. 0. 0.]
[ 0.  0.  0. -1.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[ 0.  0.  0. -1.]
[ 0.  0.  0. -1.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[ 0.  0.  0. -1.]
[ 0.  0.  0. -1.]
[ 0.  0.  0. -1.]
[0. 0. 0. 1.]
[0. 0. 0. 1.]
[0. 0. 0. 1.]
[0. 0. 0. 0.]
[0. 0. 0. 1.]


In [18]:
# OPTIMAL POLICY

env = TMazeClassicPassive(episode_length=episode_timeout, 
                          corridor_length=corridor_length, 
                          goal_reward=desired_reward)

obs = env.reset(seed=42)  # * {y, hint, flag, noise}
x0 = env.x
cue = obs[1]
done = False
step = 0
R = 0

obss = []
while not done:
    obss.append(env.render())
    print(step,'\t', obs, '\t\t', R)
    a = 0 if step != corridor_length else (1 if cue == 1 else 3)
    obs, r, done, info = env.step(a)
    step += 1
    R += r
    x = env.x

obss.append(env.render())
env.close()

print(step,'\t', obs, '\t\t', R)

0 	 [ 0. -1.  0. -1.] 		 0
1 	 [0. 0. 0. 1.] 		 0.0
2 	 [0. 0. 0. 1.] 		 0.0
3 	 [ 0.  0.  0. -1.] 		 0.0
4 	 [ 0.  0.  0. -1.] 		 0.0
5 	 [0. 0. 0. 1.] 		 0.0
6 	 [0. 0. 0. 0.] 		 0.0
7 	 [0. 0. 0. 1.] 		 0.0
8 	 [0. 0. 0. 1.] 		 0.0
9 	 [0. 0. 0. 1.] 		 0.0
10 	 [0. 0. 0. 1.] 		 0.0
11 	 [ 0.  0.  0. -1.] 		 0.0
12 	 [0. 0. 0. 1.] 		 0.0
13 	 [0. 0. 0. 0.] 		 0.0
14 	 [ 0.  0.  0. -1.] 		 0.0
15 	 [0. 0. 0. 0.] 		 0.0
16 	 [0. 0. 0. 0.] 		 0.0
17 	 [0. 0. 0. 0.] 		 0.0
18 	 [0. 0. 0. 0.] 		 0.0
19 	 [ 0.  0.  0. -1.] 		 0.0
20 	 [ 0.  0.  0. -1.] 		 0.0
21 	 [0. 0. 0. 0.] 		 0.0
22 	 [0. 0. 0. 0.] 		 0.0
23 	 [ 0.  0.  0. -1.] 		 0.0
24 	 [ 0.  0.  0. -1.] 		 0.0
25 	 [ 0.  0.  0. -1.] 		 0.0
26 	 [0. 0. 0. 1.] 		 0.0
27 	 [0. 0. 0. 1.] 		 0.0
28 	 [0. 0. 1. 1.] 		 0.0
29 	 [-1.  0.  0.  0.] 		 1.0


In [22]:
from moviepy.editor import ImageSequenceClip
import numpy as np

desired_resolution = (945, 540)
original_aspect_ratio = 112 / 64
width = int(desired_resolution[0] * original_aspect_ratio)
height = desired_resolution[1]

observations = [np.squeeze(o) for o in obss]

# Create ImageSequenceClip
clip = ImageSequenceClip(observations, fps=24)
clip = clip.resize(width=width, height=height)

# Display the modified clip
clip.ipython_display(maxduration=120)

Moviepy - Building video __temp__.mp4.
Moviepy - Writing video __temp__.mp4



Moviepy - Done !
Moviepy - video ready __temp__.mp4
